server:
  port: 8090
application:
  login: //
  password: //
  lotteryUrl: https://demo.reunico.com/api/lottery
  participantsUrl: https://demo.reunico.com/api/registered-participants
  numberingUrl: https://demo.reunico.com/api/numbering
  notifyUrl: https://demo.reunico.com/api/notify-participant
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
